#!/bin/bash
set -e -x -u

apt install \
  build-essential \
  cmake \
  debhelper \
  doxygen \
  f2c \
  freeglut3-dev \
  gfortran \
  graphviz \
  gtk-doc-tools \
  libblas-dev \
  libboost-filesystem-dev \
  libboost-iostreams-dev \
  libboost-program-options-dev \
  libboost-random-dev \
  libboost-regex-dev \
  libboost-signals-dev \
  libboost-system-dev \
  libboost-thread-dev \
  libf2c2-dev \
  libfreeimage-dev \
  libglew-dev \
  libglib2.0-dev \
  libgmp3-dev \
  libgsl0-dev \
  libgtkmm-2.4-dev \
  liblapack-dev \
  libltdl-dev \
  libopenni-dev \
  libportmidi-dev \
  libprotobuf-dev \
  libprotoc-dev \
  libqglviewer-dev \
  libqhull-dev \
  libqt4-dev \
  libqwt-dev \
  libsdl1.2-dev \
  libspnav-dev \
  libsuitesparse-dev \
  libtar-dev \
  libtbb-dev \
  libterm-readkey-perl \
  libtinyxml-dev \
  libusb-1.0-0-dev \
  libv4l-dev \
  libvtk5-dev \
  libvtk5-qt4-dev \
  libwww-perl \
  libx264-dev \
  libxml2-dev \
  libxmu-dev \
  mercurial \
  ncurses-dev \
  pkg-config \
  protobuf-compiler \
  python-dev \
  python-matplotlib \
  python-numpy \
  python-pip \
  python-pygame \
  python-pymodbus \
  python-scipy \
  python-vtk \
  python-yaml \
  spacenavd \
  subversion \
  swig
