export GUROBI_HOME="/home/manuelli/software_tools/gurobi752/linux64"
export PATH="${PATH}:${GUROBI_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${GUROBI_HOME}/lib"
export GRB_LICENSE_FILE="/home/manuelli/software_tools/gurobi.lic"
export PYTHONPATH="/home/manuelli/forces_pro:${PYTHONPATH}"