rosrun xacro xacro.py -o irb_140_ati_schunk_gelsight.urdf irb_140_ati_schunk_gelsight.urdf.xacro
rosrun xacro xacro.py -o irb_140_ati_schunk_gelsight_one_finger.urdf irb_140_ati_schunk_gelsight_one_finger.urdf.xacro
rosrun xacro xacro.py -o irb_140_ati_schunk_gelsight_less_collision.urdf irb_140_ati_schunk_gelsight_less_collision.urdf.xacro
