export LABELFUSION_SOURCE_DIR=$SPARTAN_SOURCE_DIR/src/LabelFusion
export PYTHONPATH=$PYTHONPATH:$LABELFUSION_SOURCE_DIR/modules
# export PYTHONPATH=$PYTHONPATH:$SPARTAN_INSTALL_DIR/lib/python2.7/site-packages:$SPARTAN_INSTALL_DIR/lib/python2.7/dist-packages:$SPARTAN_SOURCE_DIR/modules:$VTK_PYTHON_DIR
export PATH=$LABELFUSION_SOURCE_DIR/scripts/bin:$LABELFUSION_SOURCE_DIR/automation/scripts/bin:$PATH
alias cdlf='cd $LABELFUSION_SOURCE_DIR'