robot:
  # all paths are relative to $SPARTAN_SOURCE_DIR
  # urdf: /drake/drake/examples/kuka_iiwa_arm/models/iiwa14/iiwa14_simplified_collision.urdf
  urdf: /models/iiwa/iiwa_description/iiwa14_simplified_collision.urdf
  # options are 
  # - FIXED
  # - ROLLPITCHYAW
  # - QUATERNION (although I don't think quaternion will work at the moment)
  floatingBaseType: FIXED

data:
  # all paths are relative to $SPARTAN_SOURCE_DIR
  # the particle locations to have when adding a new contact points
  initialParticleLocations: /src/ContactParticleFilter/config/kuka_iiwa_contact_particle_filter_initial_particle_locations.out
  # the cells in mesh on which contact is allowed
  contactCells: /src/ContactParticleFilter/config/kuka_iiwa_contact_particle_filter_contact_cells.out


thresholds:
  addContactPointTimeout: 0.25
  removeContactPointTimeout: 0.25
  #add/remove thresholds should be the same
  addContactPointSquaredError: 300.0
  removeContactPointSquaredError: 300.0
  squaredErrorBoundForMostLikelyParticleAveraging: 10.0
  timeAboveThresholdToAddParticleSet: 0.2

motionModel:
  var: 0.001 #0.05
  varMin: 0.001 # 0.01
  varMax: 0.0025
  varMaxSquaredErrorCutoff: 10.0

measurementModel:
  var: 0.1

addParticleSet:
  multipleInitialSteps: False

numParticles: 50

debug:
  publishTrueResidual: True

  # toggles whether to use residual publish on "RESIDUAL_OBSERVER_STATE" or
  # or "RESIDUAL_ACTUAL"
  useTrueResidual: False
  # placeholder for now, not in use
  residualChannel: "RESIDUAL_OBSERVER_STATE" # alternate channel is "RESIDUAL_ACTUAL"
  maxNumParticleSets: 1
  forceThreshold: 1.0 # only used for plotting
  
# note this noise is not added to true residual published by externalForce
# it is only added internally before computing the various estimates . . .
noise:
  addNoise: False
  stddev: 0.1
  # maxNoise: 

vis:
  draw: False
  publish: True
  publishVisualizationData: True
  drawMostLikely: True
  drawParticles: True
  drawHistoricalMostLikely: True

solver:
  solverType: forcespro
  loadAllSolvers: False


externalForce:
  showActiveLinkEstimate: False
  publishTrueResidual: False
  initialForceMagnitude: 100

# this is the haddadin method
twoStepEstimator:
  computeEstimate: True
  visualize: False
  showContactRay: True
  # whether or not externalforce.py should be providing information about
  # which links actually have contact
  provideLinkContactInfo: False
  publishChannel: TWO_STEP_ESTIMATOR
  residualThresholdForContact: 1


# options for the proposal distribution
proposal:
  # fraction of particles that will be sampled with standard motion model
  # the remaining fraction will be sampled around the historical most likely point
  normalFraction: 0.9
  normal:
    variance: 0.001 # 0.01

  historical:
    variance: 0.00015 # 0.01
    numParticlesAtActual: 5

  seedDistribution:
    # draw randomly if squared error above this threshold
    squaredErrorThreshold: 5.0
    # draw this many particles randomly
    numParticles: 5
