"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class optitrack_marker_t(object):
    __slots__ = ["id", "xyz", "size", "params"]

    def __init__(self):
        self.id = 0
        self.xyz = [ 0.0 for dim0 in range(3) ]
        self.size = 0.0
        self.params = 0

    def encode(self):
        buf = BytesIO()
        buf.write(optitrack_marker_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">i", self.id))
        buf.write(struct.pack('>3f', *self.xyz[:3]))
        buf.write(struct.pack(">fh", self.size, self.params))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != optitrack_marker_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return optitrack_marker_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = optitrack_marker_t()
        self.id = struct.unpack(">i", buf.read(4))[0]
        self.xyz = struct.unpack('>3f', buf.read(12))
        self.size, self.params = struct.unpack(">fh", buf.read(6))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if optitrack_marker_t in parents: return 0
        tmphash = (0x547fb14424c4e573) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if optitrack_marker_t._packed_fingerprint is None:
            optitrack_marker_t._packed_fingerprint = struct.pack(">Q", optitrack_marker_t._get_hash_recursive([]))
        return optitrack_marker_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

