"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class optitrack_marker_set_t(object):
    __slots__ = ["name", "num_markers", "xyz"]

    def __init__(self):
        self.name = ""
        self.num_markers = 0
        self.xyz = []

    def encode(self):
        buf = BytesIO()
        buf.write(optitrack_marker_set_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __name_encoded = self.name.encode('utf-8')
        buf.write(struct.pack('>I', len(__name_encoded)+1))
        buf.write(__name_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">i", self.num_markers))
        for i0 in range(self.num_markers):
            buf.write(struct.pack('>3f', *self.xyz[i0][:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != optitrack_marker_set_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return optitrack_marker_set_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = optitrack_marker_set_t()
        __name_len = struct.unpack('>I', buf.read(4))[0]
        self.name = buf.read(__name_len)[:-1].decode('utf-8', 'replace')
        self.num_markers = struct.unpack(">i", buf.read(4))[0]
        self.xyz = []
        for i0 in range(self.num_markers):
            self.xyz.append(struct.unpack('>3f', buf.read(12)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if optitrack_marker_set_t in parents: return 0
        tmphash = (0xd23e993d464acde7) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if optitrack_marker_set_t._packed_fingerprint is None:
            optitrack_marker_set_t._packed_fingerprint = struct.pack(">Q", optitrack_marker_set_t._get_hash_recursive([]))
        return optitrack_marker_set_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

