"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

import optitrack.optitrack_rigid_body_t

import optitrack.optitrack_marker_t

import optitrack.optitrack_marker_set_t

class optitrack_frame_t(object):
    __slots__ = ["utime", "frame", "num_marker_sets", "marker_sets", "num_other_markers", "other_markers", "num_rigid_bodies", "rigid_bodies", "num_labeled_markers", "labeled_markers", "latency", "timecode", "timecode_subframe", "timestamp", "params"]

    def __init__(self):
        self.utime = 0
        self.frame = 0
        self.num_marker_sets = 0
        self.marker_sets = []
        self.num_other_markers = 0
        self.other_markers = []
        self.num_rigid_bodies = 0
        self.rigid_bodies = []
        self.num_labeled_markers = 0
        self.labeled_markers = []
        self.latency = 0.0
        self.timecode = 0
        self.timecode_subframe = 0
        self.timestamp = 0.0
        self.params = 0

    def encode(self):
        buf = BytesIO()
        buf.write(optitrack_frame_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qii", self.utime, self.frame, self.num_marker_sets))
        for i0 in range(self.num_marker_sets):
            assert self.marker_sets[i0]._get_packed_fingerprint() == optitrack.optitrack_marker_set_t._get_packed_fingerprint()
            self.marker_sets[i0]._encode_one(buf)
        buf.write(struct.pack(">i", self.num_other_markers))
        for i0 in range(self.num_other_markers):
            buf.write(struct.pack('>3f', *self.other_markers[i0][:3]))
        buf.write(struct.pack(">i", self.num_rigid_bodies))
        for i0 in range(self.num_rigid_bodies):
            assert self.rigid_bodies[i0]._get_packed_fingerprint() == optitrack.optitrack_rigid_body_t._get_packed_fingerprint()
            self.rigid_bodies[i0]._encode_one(buf)
        buf.write(struct.pack(">i", self.num_labeled_markers))
        for i0 in range(self.num_labeled_markers):
            assert self.labeled_markers[i0]._get_packed_fingerprint() == optitrack.optitrack_marker_t._get_packed_fingerprint()
            self.labeled_markers[i0]._encode_one(buf)
        buf.write(struct.pack(">fqqdh", self.latency, self.timecode, self.timecode_subframe, self.timestamp, self.params))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != optitrack_frame_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return optitrack_frame_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = optitrack_frame_t()
        self.utime, self.frame, self.num_marker_sets = struct.unpack(">qii", buf.read(16))
        self.marker_sets = []
        for i0 in range(self.num_marker_sets):
            self.marker_sets.append(optitrack.optitrack_marker_set_t._decode_one(buf))
        self.num_other_markers = struct.unpack(">i", buf.read(4))[0]
        self.other_markers = []
        for i0 in range(self.num_other_markers):
            self.other_markers.append(struct.unpack('>3f', buf.read(12)))
        self.num_rigid_bodies = struct.unpack(">i", buf.read(4))[0]
        self.rigid_bodies = []
        for i0 in range(self.num_rigid_bodies):
            self.rigid_bodies.append(optitrack.optitrack_rigid_body_t._decode_one(buf))
        self.num_labeled_markers = struct.unpack(">i", buf.read(4))[0]
        self.labeled_markers = []
        for i0 in range(self.num_labeled_markers):
            self.labeled_markers.append(optitrack.optitrack_marker_t._decode_one(buf))
        self.latency, self.timecode, self.timecode_subframe, self.timestamp, self.params = struct.unpack(">fqqdh", buf.read(30))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if optitrack_frame_t in parents: return 0
        newparents = parents + [optitrack_frame_t]
        tmphash = (0x192c6340cc1c6329+ optitrack.optitrack_marker_set_t._get_hash_recursive(newparents)+ optitrack.optitrack_rigid_body_t._get_hash_recursive(newparents)+ optitrack.optitrack_marker_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if optitrack_frame_t._packed_fingerprint is None:
            optitrack_frame_t._packed_fingerprint = struct.pack(">Q", optitrack_frame_t._get_hash_recursive([]))
        return optitrack_frame_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

