models:
  # Relative to DRAKE_RESOURCE_ROOT in
  # spartan/build/install/share/drake
  # WHY DRAKE WHY
  # NO THEY MADE IT WORSE
  # NOW IT HAS TO START WITH "drake"
  plate_11in: "drake/../../../../../models/dishes/plate_11in_decomp/plate_11in_decomp.urdf"
  plate_8p5in: "drake/../../../../../models/dishes/plate_8p5in_decomp/plate_8p5in_decomp.urdf"
  bowl_6p25in: "drake/../../../../../models/dishes/bowl_6p25in_decomp/bowl_6p25in_decomp.urdf"
  dish_rack: "drake/../../../../../models/dishes/dish_rack_simple.urdf"

with_ground: true

instances:
  - model: "dish_rack"
    q0: [0, 0, 0, 0, 0, 0]
    fixed: true
  - model: "plate_11in"
    q0: [0.12, -0.05, 0.3, 0.0, 0.0, 0.0]
    fixed: false
  - model: "plate_11in"
    q0: [0.12, -0.10, 0.3, 0.0, 0.0, 0.0]
    fixed: false
 # - model: "plate_11in"
 #   q0: [0.12, -0.15, 0.3, 0.0, 0.0, 0.0]
 #   fixed: false
 # - model: "plate_11in"
 #   q0: [0.12, -0.20, 0.3, 0.0, 0.0, 0.0]
 #   fixed: false
#
 # - model: "plate_8p5in"
 #   q0: [0.08, -0.30, 0.25, 0.0, 0.0, 0.0]
 #   fixed: false
 # - model: "plate_8p5in"
 #   q0: [0.08, -0.35, 0.25, 0.0, 0.0, 0.0]
 #   fixed: false
 # - model: "plate_8p5in"
 #   q0: [0.08, -0.40, 0.25, 0.0, 0.0, 0.0]
 #   fixed: false
 # - model: "plate_8p5in"
 #   q0: [0.08, -0.45, 0.25, 0.0, 0.0, 0.0]
 #   fixed: false
#
  #- model: "bowl_6p25in"
  #  q0: [0.04, -0.036, 0.9, 0.0, 0.0, 0.0]
  #  fixed: false
