models:
  # Relative to DRAKE_RESOURCE_ROOT in
  # spartan/build/install/share/drake
  # and has to start with string "drake"
  plate_11in: "drake/../../../../../models/dishes/plate_11in_decomp/plate_11in_decomp.urdf"
  plate_8p5in: "drake/../../../../../models/dishes/plate_8p5in_decomp/plate_8p5in_decomp.urdf"
  bowl_6p25in: "drake/../../../../../models/dishes/bowl_6p25in_decomp/bowl_6p25in_decomp.urdf"

with_ground: true

instances:
  - model: "plate_11in"
    q0: [0.0, 0.0, 0.1, 1.6, 0.0, .0]
    fixed: false
  - model: "plate_11in"
    q0: [0.0, 0.0, 0.15, 1.6, -0.1, .0]
    fixed: false
  - model: "plate_11in"
    q0: [0.0, 0.0, 0.20,  1.6, 0.1, .0]
    fixed: false
  - model: "plate_11in"
    q0: [0.0, 0.0, 0.25,  1.6, 0.0, .0]
    fixed: false

  - model: "plate_8p5in"
    q0: [0.0, 0.0, 0.30,  1.6, 0.2, .3]
    fixed: false
  - model: "plate_8p5in"
    q0: [0.0, 0.0, 0.35,  1.6, 0.2, .3]
    fixed: false
  - model: "plate_8p5in"
    q0: [0.0, 0.0, 0.40,  1.6, 0.2, .3]
    fixed: false
  - model: "plate_8p5in"
    q0: [0.0, 0.0, 0.45,  1.6, 0.2, .3]
    fixed: false

  - model: "bowl_6p25in"
    q0: [0.0, 0.0, 0.50,  1.6, 0.2, .3]
    fixed: false
  - model: "bowl_6p25in"
    q0: [0.0, 0.0, 0.55,  1.6, 0.0, 0.0]
    fixed: false
  - model: "bowl_6p25in"
    q0: [0.0, 0.0, 0.60,  1.6, 0.1, .0]
    fixed: false
  - model: "bowl_6p25in"
    q0: [0.0, 0.0, 0.65,  1.6, 0.1, .0]
    fixed: false